import type { Metadata } from 'next';
import './globals.css';
import { Waiting_for_the_Sunrise } from 'next/font/google';

const waitingForTheSunrise = Waiting_for_the_Sunrise({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-waiting-for-the-sunrise',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${waitingForTheSunrise.variable}`}
      suppressHydrationWarning
    >
      <body className={` antialiased`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
